# Generated by Django 5.1.5 on 2025-01-29 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_remove_aluno_tarefas_aluno_tarefas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='criado',
            new_name='criadoTime',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tarefas',
        ),
        migrations.CreateModel(
            name='TarefaConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='tarefas/')),
                ('concluido', models.BooleanField(default=False)),
                ('concluidoTime', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.aluno')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.tarefas')),
            ],
            options={
                'unique_together': {('aluno', 'tarefa')},
            },
        ),
        migrations.AddField(
            model_name='tarefas',
            name='alunos',
            field=models.ManyToManyField(related_name='tarefas_associadas', related_query_name='tarefa', through='plataforma.TarefaConcluida', to='plataforma.aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tarefas',
            field=models.ManyToManyField(related_name='alunos_associados', related_query_name='aluno', through='plataforma.TarefaConcluida', to='plataforma.tarefas'),
        ),
    ]
