# Generated by Django 5.1.5 on 2025-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_rename_criado_tarefas_criadotime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaconcluida',
            name='imagem_correcao',
            field=models.ImageField(blank=True, null=True, upload_to='tarefas/correcoes/'),
        ),
    ]
