# Generated by Django 5.1.5 on 2025-01-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_tarefaconcluida_imagem_correcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
