# Generated by Django 5.1.5 on 2025-02-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_agenda_aluno_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='agenda',
        ),
        migrations.AddField(
            model_name='aluno',
            name='aulas',
            field=models.ManyToManyField(related_name='alunos', to='plataforma.aula'),
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
