# Generated by Django 5.1.5 on 2025-02-08 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_aula_remove_aluno_agenda_aluno_aulas_delete_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaconcluida',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tarefas/'),
        ),
        migrations.AlterField(
            model_name='tarefaconcluida',
            name='imagem_correcao',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tarefas/correcoes/'),
        ),
    ]
