# Generated by Django 5.1.5 on 2025-02-10 21:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_tarefaconcluida_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Banco de Textos'), ('chart', 'Banco de Charts'), ('link', 'Banco de Links')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('chart', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='charts/')),
                ('link', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.categoriamaterial')),
            ],
        ),
    ]
