# Generated by Django 5.1.5 on 2025-02-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_categoriamaterial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='titulo',
            field=models.CharField(default='Título Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriamaterial',
            name='tipo',
            field=models.CharField(choices=[('Texto', 'Banco de Textos'), ('Chart', 'Banco de Charts'), ('Link', 'Banco de Links')], max_length=50),
        ),
    ]
